import { Fragment } from "react";
import Footer from "./components/ui/footer/footer";
import NavBar from "./components/ui/navbar/navbar";
import "./globals.css";
import { Poppins } from "next/font/google";

const poppins = Poppins({
    weight: "400",
    subsets: ["latin"],
});

export const metadata = {
    title: "Home",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={poppins.className}>
                <main className="flex flex-col min-h-screen place-content-between">
                    <NavBar />
                    <section>{children}</section>
                    <Footer />
                </main>
            </body>
        </html>
    );
}
