import { Fragment } from "react";
import Footer from "./components/ui/footer/footer";
import NavBar from "./components/ui/navbar/navbar";
import "./globals.css";
import { Poppins } from "next/font/google";
import AuthProvider from "./context/AuthProvider";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/options";

const poppins = Poppins({
    weight: "400",
    subsets: ["latin"],
});

export const metadata = {
    title: "Home",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    const secret = process.env.protection_secret;
    return (
        <html lang="en">
            <body className={poppins.className}>
                <AuthProvider>
                    <main className="flex flex-col min-h-screen h-full place-content-between">
                        <NavBar secret={secret} />
                        {children}
                        <Footer />
                    </main>
                </AuthProvider>
            </body>
        </html>
    );
}
