import NavBar from "./components/ui/navbar/navbar";
import "./globals.css";
import { Poppins } from "next/font/google";

const poppins = Poppins({
    weight: "400",
    subsets: ["latin"],
});

export const metadata = {
    title: "Home",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={poppins.className}>
                <NavBar />
                {children}
            </body>
        </html>
    );
}
